// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xonxnrmntwpifslqvfzq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhvbnhucm1udHdwaWZzbHF2ZnpxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg0NDI0NTQsImV4cCI6MjA2NDAxODQ1NH0.eAezYkgw-pjOnsBD4wWr-_ZIhKWy4l6E3FVJnH6_B30";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);